solutions/eliseworthy/config/routes.rb
FeedEngine::Application.routes.draw do
  require 'resque/server'
  mount Resque::Server, :at => "/resque" 
   
  get "items/show"

  match "/auth/:provider/callback" => "subscriptions#create"

  resources :subscriptions
  resource  :messages
  resource  :images
  resource  :links
  resources :users
  resources :items
  resources :sessions
  resources :password_resets
  resource  :dashboard,
            :controller => "dashboard",
            :only => "show"


  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  put "refeed/:id", to: "items#refeed", as: "refeed"

  # http://api.feedengine.com/feeds/foobar/items/42/refeeds.json

  constraints :subdomain => 'api', :format => :json do
    namespace :api, :path => '/' do
      namespace :v1 do
        scope "/feeds/:display_name" do
          match "/" => "items#index"
          resources :items do
            post "refeeds", to: "items#refeed"
          end
        end
      end
    end
  end

  constraints(Subdomain) do
    match "/" => "users#show"
  end

  root to: "home#index"
end

solutions/eliseworthy/app/views/layouts/_header.html.slim
div.navbar.navbar-fixed-top
  div.navbar-inner
    div.container
      a.btn.btn-navbar
      = link_to "SuperHotFeedEngine", root_url(:subdomain => false), :class => "brand"
      div.nav-collapse
        - if logged_in?
          = render :partial => "layouts/logged_in"
        - else
          = render :partial => "layouts/logged_out"

solutions/eliseworthy/app/views/layouts/_logged_in.html.slim
ul.nav.pull-right
  li= link_to "#{current_user.subdomain}'s Feed", root_url(:subdomain => current_user.subdomain)
  li= link_to "Dashboard", dashboard_url(:subdomain => false)
  li= link_to "Log out", logout_url(:subdomain => false)

solutions/eliseworthy/app/views/layouts/_logged_out.html.slim
ul.nav.pull-right
  li= link_to "Log in", login_url(:subdomain => false)
  li= link_to "Sign up", signup_url(:subdomain => false)

solutions/eliseworthy/app/views/layouts/application.html.slim
doctype 5
html
head
  title FeedEngine
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  == yield :head
body
  = render :partial => "layouts/header"
  div.container#main-content
    - flash.each do |type, message|
      div class="alert alert-#{type}"
        = raw(message)

    == yield