solutions/cstrahan/config/routes.rb
FeedEngine::Application.routes.draw do
  get "static_pages/show"

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}


  # User subdomains
  scope "", constraints: Subdomains.user_feeds do
    match "", to: "users#show"
  end

  # Api subdomain
  scope module: "api", as: "api", constraints: Subdomains.api do
    resources "users", only: [:index]
    resources "relationships", only: [:index]
    resources "feeds" do
      collection do
        scope ":user_display_name" do
          resources "items" do
            resources "refeeds"
          end
        end
      end
    end
  end

  resources "feeds" do
    collection do
      scope ":user_display_name" do
        resources "items"
      end
    end
  end

  resources "users", as: :user do
    member do
      get :following, :followers, :refeeds
    end
  end

  match "/auth/twitter/callback" => "authentications#twitter"
  match "/auth/github/callback" => "authentications#github"
  match "/auth/instagram/callback" => "authentications#instagram"
  match "/auth/failure" => "authentications#failure"
  match "/user_signup_steps/finish" => "user_signup_steps#finish"

  resource "dashboard"
  resources "text_posts"
  resources "image_posts"
  resources "link_posts"
  resources "feed_items"
  resources "authentications", only: [:show, :destroy]
  resources "points", only: [:create]
  resources "refeeds", only: [:create]
  resources "user_signup_steps"
  resources "relationships", only: [:create, :destroy, :index]

  root :to => "static_pages#show"

  devise_scope :user do
    get "login" => "devise/sessions#new", :as => :login
    delete "/logout" => "devise/sessions#destroy"
    get "signup" => "registrations#new", :as => :new_user
  end

  root :to => "dashboards#show"
end

solutions/cstrahan/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      render "edit"
    end
  end
end

solutions/cstrahan/app/views/settings/edit_settings.html.slim
h2
  | Edit #{resource_name.to_s.humanize} TOMOOMOTOMT
= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f|
  = f.error_notification
  .inputs
    = f.input :email, :required => true, :autofocus => true
    = f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false
    = f.input :password_confirmation, :required => false
    = f.input :current_password, :hint => "we need your current password to confirm your changes", :required => false
  .actions
    = f.button :submit, "Update"
br
br
p
  | Unhappy? #{link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete}.
= link_to "Back", :back